config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#index'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'profile' => 'users#edit'
  put 'profile' => 'users#update'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'dashboard' => 'dashboard#index'

  resources :users, only: [:new, :create, :edit, :update]
  resources :products, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :orders, only: [:create]
end

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Ecommerce App', root_path, class:'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user %>
          <li>
            <%= link_to 'Login', login_path %>
          </li>
          <li>
            <%= link_to 'Signup', signup_path %>
          </li>
        <% else %>
        <li>
          <%= link_to 'Dashboard', dashboard_path %>
        </li>
        <li>
          <%= link_to 'Profile', profile_path %>
        </li>
        <li role="separator" class="divider"></li>
        <li>
          <%= link_to 'Logout', logout_path, method: :delete %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>