config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'root#index'

  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'profile' => 'users#edit'
  put 'profile' => 'users#update'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'dashboard' => 'dashboard#index'

  resources :users, only: [:new, :create, :edit, :update]
  resources :products, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :orders, only: [:create]
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :orders

  validates :name, length: { in: 1..30 }
  validates :original_price, numericality: {greater_than: 0}
  validates :discounted_price, numericality: {greater_than: 0}

  validate :original_greater_than_discount

  # has_attached_file :image, styles: {
    # thumb: '100x100>',
    # square: '200x200#',
    # medium: '300x300>',
    # large: '600x600>'
  # }
  has_attached_file :image

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def original_greater_than_discount
    errors.add(:original_price, "must be more than or equal to discounted price") unless original_price >= discounted_price
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :is_authenticated
  before_action :user_is_seller, except: [:show]
  before_action :js_only, except: [:show]
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :product_is_available, only: [:show]

  def new
    @product = Product.new
    render :form
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    if @product.save
      flash[:success] = "Successfully added product."
      redirect_to dashboard_path(:store => true)
    else
      flash[:danger] = "Unable to add product. Please check parameters."
      render :addform
    end
  end

  def show
  end

  def edit
    render :form
  end

  def update
    if !product_params[:image]
      product_params[:image] = @product.image
    end
    if @product.update(product_params)
      flash[:success] = "Successfully updated product."
      redirect_to dashboard_path(:store => true)
    else
      flash[:danger] = "Unable to update product. Please check parameters."
      render :form
    end
  end

  def destroy
    if @product.update(status: 'removed')
      flash[:success] = "Successfully removed product."
      redirect_to dashboard_path(:store => true)
    else
      flash[:danger] = "Unable to remove product."
      render :form
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :status, :original_price, :discounted_price, :image)
  end

  def js_only
    if request.format != 'js'
      redirect_to products_url, notice: 'Error. Javascript Only.'
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_addform.html.erb
<div class='add_product'>
  <div class='product-form'>
    <h2>Add Product</h2>
    <%= form_for(@product, remote: true, :html => { id:"add-product"} ) do |f| %>

      <% if @product.errors.any? %>
        <% @product.errors.full_messages.each do |message| %>
          <div class="alert alert-danger">
            <%= message %>
          </div>
        <% end %>
      <% end %>

      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", :required => true %>
      </div>

      <div class="form-group">
        <%= f.label :original_price, 'Original Price' %>
        <%= f.number_field :original_price, min: 0.01, step: 0.01, class: "form-control", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :discounted_price, 'Discounted Price' %>
        <%= f.number_field :discounted_price, min: 0.01, step: 0.01, class: "form-control", required: true %>
      </div>

      <div class="form-group">
        <%= f.label :status, "Available" %>
        <%= f.select :status, [['Yes', 'available'],['No', 'unavailable']], class: "form-control", :required => true %>
      </div>

      <div class="form-group">
        <%= f.label :image, 'Image' %>
        <%= f.file_field :image, accept: 'image/*', :required => true%>
      </div>

      <%= f.submit 'Add', class: "updating-product btn-full btn btn-success"  %>
      <script>
      $('.updating-product').submit(function (e) {
        e.preventDefault()
        $('<p style="color:red;">Uploading Please wait...</p>').insertBefore(this)
      })
      </script>
    <% end %>
  </div>
</div>

app/views/products/_form.html.erb
<div class='product-form'>
  <h2>Update Product</h2>
  <%= form_for(@product, remote: true, :html => { id:"add-product"} ) do |f| %>

    <% if @product.errors.any? %>
      <% @product.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <%= message %>
        </div>
      <% end %>
    <% end %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control", :required => true %>
    </div>

    <div class="form-group">
      <%= f.label :original_price, 'Original Price' %>
      <%= f.number_field :original_price, min: 0.01, step: 0.01, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :discounted_price, 'Discounted Price' %>
      <%= f.number_field :discounted_price, min: 0.01, step: 0.01, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :status, "Available" %>
      <%= f.select :status, [['Yes', 'available'],['No', 'unavailable']], class: "form-control", :required => true %>
    </div>

    <div class="form-group">
      <%= f.label :image, 'Image' %>
      <% if @product.image_file_name  %>
        <br>
        <%= image_tag(@product.image, width: 200, crop: :fill) %>
        <%= f.file_field :image, accept: 'image/*'%>
      <% else %>
        <%= f.file_field :image, accept: 'image/*', :required => true%>
      <% end %>
    </div>

    <%= f.submit 'Update', class: "btn-full btn btn-success"  %>
    <script>
    $('.updating-product').submit(function (e) {
      e.preventDefault()
      $('<p style="color:red;">Uploading Please wait...</p>').insertBefore(this)
    })
    </script>
  <% end %>

  <script>
    function hideEdit() {
      $('.edit_product').hide()
      $(".add_product").show()
    }
  </script>

  <button onclick=hideEdit() class='btn-full btn-cancel btn'>Cancel</button>
</div>

app/views/products/_index.html.erb
<div class='col-xs-12 col-sm-12 col-md-8'>
  <div class="all-product">
    <% if @products.count < 1 %>
      <div class='col-xs-12'>
        <p>
          You have no products in your store at the moment. You may wish to add a product.
        </p>
      </div>
    <% else %>
      <% if @products_available.count > 0 %>
        <div class='col-xs-12'>
          <h1>Selling</h1>
        </div>
        <% @products_available.each do |product| %>
          <div class='col-xs-12 col-sm-6 col-md-4'>
            <div class='root-product-container' >
              <div class='root-product-image-container'>
                <%= link_to image_tag(product.image, alt:'product-image', class:'root-product-image'), product%>
              </div>
              <div class='root-product-information-container'>
                <p class='root-product-name'>
                  <%= product.name%>
                </p>
                <p class='root-product-seller'>
                  <%= product.user.first_name%>
                </p>
                <div class='root-product-prices-container'>
                  <span class='root-product-discounted-price'>
                    <%= number_to_currency(product.discounted_price, precision: 2, locale: :en)%>
                  </span>
                  <% if product.original_price != product.discounted_price %>
                  <span class='root-product-original-price'>
                    <%= number_to_currency(product.original_price, precision: 2, locale: :en)%>
                  </span>
                  <% end %>
                  <span class='product-edit'>
                    <%= link_to 'Edit', edit_product_path(product), remote: true %>
                    <%= ' | '%>
                    <%= link_to 'Remove', product_path(product), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
                  </span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <% if @products_unavailable.count > 0 %>
        <div class='col-xs-12'>
          <h1>Unavailable Products</h1>
        </div>
        <% @products_unavailable.each do |product| %>
          <div class='col-xs-12 col-sm-12 col-md-4'>
            <div class='root-product-container' >
              <div class='root-product-image-container'>
                <%= link_to image_tag(product.image, alt:'product-image', class:'root-product-image'), product%>
              </div>
              <div class='root-product-information-container'>
                <p class='root-product-name'>
                  <%= product.name%>
                </p>
                <p class='root-product-seller'>
                  <%= product.user.first_name%>
                </p>
                <div class='root-product-prices-container'>
                  <span class='root-product-discounted-price'>
                    <%= number_to_currency(product.discounted_price, precision: 2, locale: :en)%>
                  </span>
                  <% if product.original_price != product.discounted_price %>
                  <span class='root-product-original-price'>
                    <%= number_to_currency(product.original_price, precision: 2, locale: :en)%>
                  </span>
                  <% end %>
                  <span class='product-edit'>
                    <%= link_to 'Edit', edit_product_path(product), remote: true %>
                    <%= ' | '%>
                    <%= link_to 'Remove', product_path(product), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
                  </span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class='col-xs-12 col-sm-12 col-md-4'>
  <!-- <div class='add_product'>
    <div class='product-form'>
      <h2>Add Product</h2>
      <%= form_for(@product, remote: true, :html => { id:"add-product"} ) do |f| %>

        <% if @product.errors.any? %>
          <% @product.errors.full_messages.each do |message| %>
            <div class="alert alert-danger">
              <%= message %>
            </div>
          <% end %>
        <% end %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control", :required => true %>
        </div>

        <div class="form-group">
          <%= f.label :original_price, 'Original Price' %>
          <%= f.number_field :original_price, min: 0.01, step: 0.01, class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :discounted_price, 'Discounted Price' %>
          <%= f.number_field :discounted_price, min: 0.01, step: 0.01, class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :status, "Available" %>
          <%= f.select :status, [['Yes', 'available'],['No', 'unavailable']], class: "form-control", :required => true %>
        </div>

        <div class="form-group">
          <%= f.label :image, 'Image' %>
          <%= f.file_field :image, accept: 'image/*', :required => true%>
        </div>

        <%= f.submit 'Add', class: "updating-product btn-full btn btn-success"  %>
        <script>
        $('.updating-product').submit(function (e) {
          e.preventDefault()
          $('<p style="color:red;">Uploading Please wait...</p>').insertBefore(this)
        })
        </script>
      <% end %>
    </div>
  </div> -->
  <%= render "products/addform" %>

  <div class="edit_product"></div>

</div>

app/views/products/_show.html.erb
<div class="row">
  <div class="col s12 m6">
    <div class="card darken-1">
      <div class="card-content">
        <span class="card-title"><%= product.name %></span>
        <p><%= product.description %></p>
      </div>
      <div class="card-action">
        <%= link_to 'Edit', edit_product_path(product), remote: true %>
        <!-- <%= link_to 'Destroy', product, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %> -->
      </div>
    </div>
  </div>
</div>

app/views/products/addform.js.erb
$(".edit_product").hide()
$(".add_product").show()
$(".add_product").html(
  "<%= escape_javascript(render partial: 'addform', locals: { product: @product } ) %>"
)

app/views/products/form.js.erb
$(".add_product").hide()
$(".edit_product").show()
$(".edit_product").html(
  "<%= escape_javascript(render partial: 'form', locals: { product: @product } ) %>"
)

app/views/products/index.html.erb
<div class='col-xs-12 col-sm-12 col-md-8'>
  <div class="all-product">
    <% if @products.count < 1 %>
      <div class='col-xs-12'>
        <p>
          You have no products in your store at the moment. You may wish to add a product.
        </p>
      </div>
    <% else %>
      <% if @products_available.count > 0 %>
        <div class='col-xs-12'>
          <h1>Selling</h1>
          <!-- <%= button_to 'Add', new_product_path, method: :get, remote: true, class:'add-btn btn btn-success' %> -->
        </div>
        <% @products_available.each do |product| %>
          <div class='col-xs-12 col-sm-12 col-md-4'>
            <div class='root-product-container' >
              <div class='root-product-image-container'>
                <%= link_to image_tag(product.image, alt:'product-image', class:'root-product-image'), product%>
              </div>
              <div class='root-product-information-container'>
                <p class='root-product-name'>
                  <%= product.name%>
                </p>
                <p class='root-product-seller'>
                  <%= product.user.first_name%>
                </p>
                <div class='root-product-prices-container'>
                  <span class='root-product-discounted-price'>
                    <%= number_to_currency(product.discounted_price, precision: 2, locale: :en)%>
                  </span>
                  <% if product.original_price != product.discounted_price %>
                  <span class='root-product-original-price'>
                    <%= number_to_currency(product.original_price, precision: 2, locale: :en)%>
                  </span>
                  <% end %>
                  <span class='product-edit'>
                    <%= link_to 'Edit', edit_product_path(product), remote: true %>
                    <%= ' | '%>
                    <%= link_to 'Remove', product_path(product), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
                  </span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      <% if @products_unavailable.count > 0 %>
        <div class='col-xs-12'>
          <h1>Unavailable Products</h1>
        </div>
        <% @products_unavailable.each do |product| %>
          <div class='col-xs-12 col-sm-12 col-md-4'>
            <div class='root-product-container' >
              <div class='root-product-image-container'>
                <%= link_to image_tag(product.image, alt:'product-image', class:'root-product-image'), product%>
              </div>
              <div class='root-product-information-container'>
                <p class='root-product-name'>
                  <%= product.name%>
                </p>
                <p class='root-product-seller'>
                  <%= product.user.first_name%>
                </p>
                <div class='root-product-prices-container'>
                  <span class='root-product-discounted-price'>
                    <%= number_to_currency(product.discounted_price, precision: 2, locale: :en)%>
                  </span>
                  <% if product.original_price != product.discounted_price %>
                  <span class='root-product-original-price'>
                    <%= number_to_currency(product.original_price, precision: 2, locale: :en)%>
                  </span>
                  <% end %>
                  <span class='product-edit'>
                    <%= link_to 'Edit', edit_product_path(product), remote: true %>
                    <%= ' | '%>
                    <%= link_to 'Remove', product_path(product), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
                  </span>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<div class='col-xs-12 col-sm-12 col-md-4'>
  <div class='add_product'>
    <div class='product-form'>
      <h2>Add Product</h2>
      <%= form_for(@product, remote: true, :html => { id:"add-product"} ) do |f| %>

        <% if @product.errors.any? %>
          <% @product.errors.full_messages.each do |message| %>
            <div class="alert alert-danger">
              <%= message %>
            </div>
          <% end %>
        <% end %>

        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: "form-control", :required => true %>
        </div>

        <div class="form-group">
          <%= f.label :original_price, 'Original Price' %>
          <%= f.number_field :original_price, min: 0.01, step: 0.01, class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :discounted_price, 'Discounted Price' %>
          <%= f.number_field :discounted_price, min: 0.01, step: 0.01, class: "form-control", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :status, "Available" %>
          <%= f.select :status, [['Yes', 'available'],['No', 'unavailable']], class: "form-control", :required => true %>
        </div>

        <div class="form-group">
          <%= f.label :image, 'Image' %>
          <%= f.file_field :image, accept: 'image/*', :required => true%>
        </div>

        <%= f.submit 'Add', class: "updating-product btn-full btn btn-success"  %>
        <script>
        $('.updating-product').submit(function (e) {
          e.preventDefault()
          $('<p style="color:red;">Uploading Please wait...</p>').insertBefore(this)
        })
        </script>

      <% end %>
    </div>
  </div>

  <div class="edit_product"></div>

</div>

app/views/products/show.html.erb
<div class='show-product-container'>
  <div class='show-product-image-container'>
    <%= image_tag(@product.image, alt:'product-image', class:'show-product-image')%>
  </div>
  <div class='col-sm-12 col-md-9'>
    <div class='show-product-information-container'>
      <p class='show-product-name'>
        <%= @product.name%>
      </p>
      <p class='show-product-seller'>
        <%= @product.user.first_name%>
      </p>
      <p class='show-product-description'>
        <%= @product.description %>
      </p>
    </div>
  </div>
  <div class='col-sm-12 col-md-3'>
    <div class='show-product-order-container'>
      <div class='show-product-prices-container'>
        <span class='show-product-discounted-price'>
          <%= number_to_currency(@product.discounted_price, precision: 2, locale: :en)%>
        </span>
        <span class='show-product-original-price'>
          <%= number_to_currency(@product.original_price, precision: 2, locale: :en)%>
        </span>
      </div>

      <% if @product.user != current_user%>
        <%= form_tag orders_path(:product => @product) do %>
          <article>
            <% if flash[:error].present? %>
              <div id="error_explanation">
                <p><%= flash[:error] %></p>
              </div>
              <% end %>
          </article>
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description=<%= @product.name %>
                data-amount=<%= @product.discounted_price*100 %>
                data-locale="auto">
          </script>
          <!-- <script>
          document.getElementsByClassName("stripe-button-el")[0].style.display = 'none';
          </script>
          <button type="submit" class="order-btn btn btn-success">Buy</button> -->
        <% end %>
      <% else %>
        <p>
          You are selling this product.
        </p>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.js.erb
$("#add_edit_product").hide();
$("#show_product").show();
$("#show_product").html("<%= escape_javascript(render partial: 'show', locals: { product: @product } ) %>");